apiVersion: v1
kind: Pod
metadata:
  name: netshoot
  namespace: socaas-soar
  labels:
    app.kubernetes.io/name: netshoot
spec:
  restartPolicy: Never
  containers:
    - name: netshoot
      image: nicolaka/netshoot:latest
      command: ["sleep", "3600"]
      resources:
        requests:
          cpu: 25m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi
